---
version: "3.7"
services:
  kasm:
    build: .
    image: ghcr.io/capsulecorplab/kasm-sealion-workspace:dev
    ports:
      - "6901:6901"
      - "50000:50000"
    environment:
      VNC_PW: password
    shm_size: '512m'
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    network_mode: bridge
    volumes:
      - type: bind
        source: ./kasm_user
        target: /home/kasm-user
#      - type: bind
#        source: /run/user/1000/pulse/
#        target: /run/user/1000/pulse/
    security_opt:
      - seccomp=unconfined
...
